interface IVehicle {
    name: string,
    color: string,
    category: string,
    subCategory?: string,
    licensePlate: string,
    vanSize: number,
    driverLicense?: string,
    description1?: string,
    description2?: string,
    images: string
}

const vehicles: IVehicle[] = [
    {
        name: 'Tesla Model 3',
        color: 'Red',
        category: 'luxury',
        licensePlate: 'XXXX-YYY',
        vanSize: 4,
        driverLicense: 'B',
        description1: 'Model 3 has a 310 mile range, 0-60 mph acceleration in 3.2 seconds and our most refined design and engineering ever.',
        description2: 'Model 3 has a 310 mile range, 0-60 mph acceleration in 3.2 seconds and our most refined design and engineering ever.',
        images: 'TeslaModel3.jpg'
    },
    {
        name: 'Lexus ES',
        color: 'White',
        category: 'luxury',
        licensePlate: 'XXXX-YYY',
        vanSize: 4,
        driverLicense: 'B',
        description1: 'Explore the 2020 Lexus ES and ES Hybrid galleries to view distinctive styling with dynamic performance. Look into the Lexus ES line today.',
        description2: 'Explore the 2020 Lexus ES and ES Hybrid galleries to view distinctive styling with dynamic performance. Look into the Lexus ES line today.',
        images: 'LexusES.jpg'
    },
    {
        name: 'Mercedes-Benz C-Class',
        color: 'Silver',
        category: 'luxury',
        licensePlate: 'XXXX-YYY',
        vanSize: 4,
        driverLicense: 'B',
        description1: 'The C-Class (BR 205): The most successful Mercedes-Benz model series is entering its fifth year of production with extensive modifications.',
        description2: 'The C-Class (BR 205): The most successful Mercedes-Benz model series is entering its fifth year of production with extensive modifications.',
        images: 'Mercedes-Benz C-Class.jpg'
    },
    {
        name: 'Honda Odyssey',
        color: 'White',
        category: 'van',
        licensePlate: 'XXXX-YYY',
        vanSize: 7,
        driverLicense: 'B',
        description1: 'The Honda Odyssey is ranked #1 in Minivans by U.S. News & World Report. See the review, prices, pictures and all our rankings.',
        description2: 'The Honda Odyssey is ranked #1 in Minivans by U.S. News & World Report. See the review, prices, pictures and all our rankings.',
        images: 'Honda Odyssey.jpg'
    },
    {
        name: 'Chrysler Pacifica',
        color: 'Silver',
        category: 'van',
        licensePlate: 'XXXX-YYY',
        vanSize: 7,
        driverLicense: 'B',
        description1: 'The Chrysler Pacifica is a family minivan. Explore 8 passenger seating, available hybrid option, & other features. Build and price a Pacifica.',
        description2: 'The Chrysler Pacifica is a family minivan. Explore 8 passenger seating, available hybrid option, & other features. Build and price a Pacifica.',
        images: 'Chrysler Pacifica.jpg'
    },
    {
        name: 'Mercedes-Benz Metris',
        color: 'Black',
        category: 'van',
        licensePlate: 'XXXX-YYY',
        vanSize: 7,
        driverLicense: 'B',
        description1: 'Research the 2019 Mercedes-Benz Metris at cars.com and find specs, pricing, MPG, safety data, photos, videos, reviews and local inventory.',
        description2: 'Research the 2019 Mercedes-Benz Metris at cars.com and find specs, pricing, MPG, safety data, photos, videos, reviews and local inventory.',
        images: 'Mercedes-Benz Metris.jpg'
    },
    {
        name: 'Volvo XC40 T3',
        color: 'Blue',
        category: 'business',
        licensePlate: 'XXXX-YYY',
        vanSize: 4,
        driverLicense: 'B',
        description1: `Volvo's first three- pot motor and standard suspension settings aren't so flattering in a car that's markedly better to drive in other forms.`,
        description2: `Volvo's first three - pot motor and standard suspension settings aren't so flattering in a car that's markedly better to drive in other forms.`,
        images: 'Volvo XC40 T3.jpg'
    },
    {
        name: 'Mazda CX-30',
        color: 'Red',
        category: 'business',
        licensePlate: 'XXXX-YYY',
        vanSize: 4,
        driverLicense: 'B',
        description1: `The all-new 2020 Mazda CX-30 is a crossover SUV slotted between the subcompact CX-3 and compact CX-5.`,
        description2: `The all-new 2020 Mazda CX-30 is a crossover SUV slotted between the subcompact CX-3 and compact CX-5.`,
        images: 'Mazda CX-30.jpg'
    },
    {
        name: 'Renault Clio',
        color: 'Yellow',
        category: 'business',
        licensePlate: 'XXXX-YYY',
        vanSize: 4,
        driverLicense: 'B',
        description1: `The Renault Clio is a supermini car (B-segment), produced by the French automobile manufacturer Renault. It was launched in 1990, and was in its fourth generation in 2012.`,
        description2: `The Renault Clio is a supermini car (B-segment), produced by the French automobile manufacturer Renault. It was launched in 1990, and was in its fourth generation in 2012. `,
        images: 'Renault Clio.jpg'
    },
    {
        name: 'KTM 390 Duke',
        color: 'Orange',
        category: 'motorcycle',
        subCategory: 'Lightweight',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'A',
        description1: 'Explore KTM 390 Duke Price in India, Specs, Features, Mileage, KTM 390 Duke Images, KTM News, 390 Duke Review and all other KTM bikes.',
        description2: 'Explore KTM 390 Duke Price in India, Specs, Features, Mileage, KTM 390 Duke Images, KTM News, 390 Duke Review and all other KTM bikes.',
        images: 'KTM 390 Duke.jpg'
    },
    {
        name: 'Kawasaki Eliminator 125',
        color: 'Red',
        category: 'motorcycle',
        subCategory: 'Lightweight',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'A',
        description1: 'Kawasaki EL 125 Eliminator. Year. 2009 - 10. Engine. Four stroke, single cylinder, SOHC, 2 valve. Capacity. 124 cc / 7.6 cu-in. Bore x Stroke, 55 x 52.4 mm.',
        description2: 'Kawasaki EL 125 Eliminator. Year. 2009 - 10. Engine. Four stroke, single cylinder, SOHC, 2 valve. Capacity. 124 cc / 7.6 cu-in. Bore x Stroke, 55 x 52.4 mm.',
        images: 'kawasaki eliminator 125.jpg'
    },
    {
        name: 'Kawasaki Ninja 300',
        color: 'Green',
        category: 'motorcycle',
        subCategory: 'Lightweight',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'A',
        description1: 'The diamond frame in Ninja 300 features new high-tensile steel components (known as special steels which develop high yield, tensile and fatigue strengths, as well as excellent toughness), which offers high strength and high durability – both essential in a high-performance frame.',
        description2: 'The diamond frame in Ninja 300 features new high-tensile steel components (known as special steels which develop high yield, tensile and fatigue strengths, as well as excellent toughness), which offers high strength and high durability – both essential in a high-performance frame.',
        images: 'Kawasaki Ninja 300.jpg'
    },
    {
        name: 'Suzuki SV650',
        color: 'Blue',
        category: 'motorcycle',
        subCategory: 'Middleweight',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'A',
        description1: 'The long-lived and hugely popular SV is the bike that kick started the middleweight naked class when first launched in 1999.',
        description2: 'The long-lived and hugely popular SV is the bike that kick started the middleweight naked class when first launched in 1999.',
        images: 'Suzuki SV650.jpg'
    },
    {
        name: 'Yamaha MT-07',
        color: 'Blue',
        category: 'motorcycle',
        subCategory: 'Middleweight',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'A',
        description1: 'Motorcycling generally got a shot in the arm when Yamaha began introducing its all-new, modular, budget-priced MT range from 2013 and its mid-range, 689cc, twin cylinder version (there’s also the original 847cc MT-09 triple plus a single) is arguably the pick of the bunch and has proved a Europe-wide hit.',
        description2: 'Motorcycling generally got a shot in the arm when Yamaha began introducing its all-new, modular, budget-priced MT range from 2013 and its mid-range, 689cc, twin cylinder version (there’s also the original 847cc MT-09 triple plus a single) is arguably the pick of the bunch and has proved a Europe-wide hit.',
        images: 'Yamaha MT-07.jpg'
    },
    {
        name: 'Ducati Monster 797',
        color: 'Red',
        category: 'motorcycle',
        subCategory: 'Middleweight',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'A',
        description1: 'Ducati’s stylish and charismatic Monsters have been a great and often affordable introduction to Italian exotica ever since the original 900 in 1993.',
        description2: 'Ducati’s stylish and charismatic Monsters have been a great and often affordable introduction to Italian exotica ever since the original 900 in 1993.',
        images: 'Ducati Monster 797.jpg'
    },
    {
        name: 'HONDA GROM',
        color: 'Red',
        category: 'motorcycle',
        subCategory: 'Superbike',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'A',
        description1: 'The Honda Grom has got to be one of my favorite bikes currently on the market, because it captures the pocket-rocket aesthetic in a street legal package.',
        description2: 'The Honda Grom has got to be one of my favorite bikes currently on the market, because it captures the pocket-rocket aesthetic in a street legal package.',
        images: 'HONDA GROM.jpg'
    },
    {
        name: 'SUZUKI GSX 250R',
        color: 'Black',
        category: 'motorcycle',
        subCategory: 'Superbike',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'A',
        description1: `The GSX250R is one of Suzuki's newest additions to their product line, not to be confused with the GSX-R series.`,
        description2: `The GSX250R is one of Suzuki's newest additions to their product line, not to be confused with the GSX-R series.`,
        images: 'SUZUKI GSX 250R.jpg'
    },
    {
        name: 'HONDA CBR500R',
        color: 'Black',
        category: 'motorcycle',
        subCategory: 'Superbike',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'A',
        description1: `The Honda CBR500R is one of three in the Honda CBR500 series, all of which are equipped with a 471cc engine, putting out about 46 horsepower.`,
        description2: `The Honda CBR500R is one of three in the Honda CBR500 series, all of which are equipped with a 471cc engine, putting out about 46 horsepower.`,
        images: 'HONDA CBR500R.jpg'
    },
    {
        name: 'Ferrari FXX-K',
        color: 'Blue',
        category: 'sport_cars',
        subCategory: 'Ferrari',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'B',
        description1: `The Ferrari FXX K is a high performance limited production track day car manufactured by automobile manufacturer Ferrari in Maranello, Italy.`,
        description2: `The Ferrari FXX K is a high performance limited production track day car manufactured by automobile manufacturer Ferrari in Maranello, Italy.`,
        images: 'Ferrari FXX-K.jpg'
    },
    {
        name: 'Ferrari 488 GTB',
        color: 'Red',
        category: 'sport_cars',
        subCategory: 'Ferrari',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'B',
        description1: `The Ferrari 488 (Type F142M) is a mid-engine sports car produced by the Italian automobile manufacturer Ferrari.`,
        description2: `The Ferrari 488 (Type F142M) is a mid-engine sports car produced by the Italian automobile manufacturer Ferrari.`,
        images: 'Ferrari 488 GTB.jpg'
    },
    {
        name: 'Ferrari FXX-K Evo',
        color: 'Black',
        category: 'sport_cars',
        subCategory: 'Ferrari',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'B',
        description1: `The FXX-K Evo was unveiled at the Ferrari Finali Mondiali 2017 on 28 October 2017 at Stazione Leopolda in Florence during the Ferrari 70th Anniversary celebration.`,
        description2: `The FXX-K Evo was unveiled at the Ferrari Finali Mondiali 2017 on 28 October 2017 at Stazione Leopolda in Florence during the Ferrari 70th Anniversary celebration.`,
        images: 'Ferrari FXX-K Evo.jpg'
    },
    {
        name: '488 GT3',
        color: 'Red',
        category: 'sport_cars',
        subCategory: 'Ferrari',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'B',
        description1: `The FERRARI 488 GT3 made its world competition debut in Round 2 of the 2016 Australian GT Championship at the Albert Park Circuit in Melbourne on 17 March (the round was run as a support category to the 2016 Australian Grand Prix).`,
        description2: `The FERRARI 488 GT3 made its world competition debut in Round 2 of the 2016 Australian GT Championship at the Albert Park Circuit in Melbourne on 17 March (the round was run as a support category to the 2016 Australian Grand Prix).`,
        images: '488 GT3.jpg'
    },
    {
        name: 'Ferrari 599 Gtb Fiorano',
        color: 'Yellow',
        category: 'sport_cars',
        subCategory: 'Ferrari',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'B',
        description1: `The Ferrari 599 GTB Fiorano (internal code F141) is a grand tourer produced by Italian automobile manufacturer Ferrari. It was the brand's front engined, two-seat flagship, replacing the 575M Maranello in 2006 as a 2007 model, and was replaced for the 2013 model year by the F12berlinetta.`,
        description2: `The Ferrari 599 GTB Fiorano (internal code F141) is a grand tourer produced by Italian automobile manufacturer Ferrari. It was the brand's front engined, two-seat flagship, replacing the 575M Maranello in 2006 as a 2007 model, and was replaced for the 2013 model year by the F12berlinetta.`,
        images: 'Ferrari 599 Gtb Fiorano.jpg'
    },
    {
        name: 'McLaren 12C',
        color: 'Silver',
        category: 'sport_cars',
        subCategory: 'McLaren',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'B',
        description1: `The McLaren MP4-12C, later known simply as the McLaren 12C,[3] is a sports car designed and manufactured by McLaren Automotive. It is the first ever production car wholly designed and built by McLaren,[4] and their first production road car produced since the McLaren F1, which ended production in 1998. The car's final design was unveiled in September 2009 and was launched in mid-2011.`,
        description2: `The McLaren MP4-12C, later known simply as the McLaren 12C,[3] is a sports car designed and manufactured by McLaren Automotive. It is the first ever production car wholly designed and built by McLaren,[4] and their first production road car produced since the McLaren F1, which ended production in 1998. The car's final design was unveiled in September 2009 and was launched in mid-2011.`,
        images: 'McLaren 12C.jpg'
    },
    {
        name: 'McLaren 650SC',
        color: 'Orange',
        category: 'sport_cars',
        subCategory: 'McLaren',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'B',
        description1: `The McLaren 650S is a British sports car designed and manufactured by British automobile manufacturer McLaren Automotive. It was announced in February 2014 as a new model, but based on the existing MP4-12C with 25% new parts, and was formally unveiled at the 2014 Geneva Motor Show.`,
        description2: `The McLaren 650S is a British sports car designed and manufactured by British automobile manufacturer McLaren Automotive. It was announced in February 2014 as a new model, but based on the existing MP4-12C with 25% new parts, and was formally unveiled at the 2014 Geneva Motor Show.`,
        images: 'McLaren 650S.jpg'
    },
    {
        name: 'Pagani Zonda',
        color: 'Sliver',
        category: 'sport_cars',
        subCategory: 'Pagani',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'B',
        description1: `The Pagani Zonda is a mid-engine sports car produced by the Italian sports car manufacturer Pagani. It debuted at the 1999 Geneva Motor Show. By 2018, a total of 140 cars had been built, including development mules. Both 2-door coupé and roadster variants have been produced along with a third new variant being the barchetta. Construction is mainly of carbon fibre.`,
        description2: `The Pagani Zonda is a mid-engine sports car produced by the Italian sports car manufacturer Pagani. It debuted at the 1999 Geneva Motor Show. By 2018, a total of 140 cars had been built, including development mules. Both 2-door coupé and roadster variants have been produced along with a third new variant being the barchetta. Construction is mainly of carbon fibre.`,
        images: 'Pagani Zonda.jpg'
    },
    {
        name: 'Pagani Zonda C12',
        color: 'Sliver',
        category: 'sport_cars',
        subCategory: 'Pagani',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'B',
        description1: `Pagani pulled the cover off of its very first vehicle: the Zonda C12. It's the latest subject of our new series, Supercar Sunday`,
        description2: `Pagani pulled the cover off of its very first vehicle: the Zonda C12. It's the latest subject of our new series, Supercar Sunday`,
        images: 'Pagani Zonda C12.jpg'
    },
    {
        name: 'Zonda S',
        color: 'Red',
        category: 'sport_cars',
        subCategory: 'Pagani',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'B',
        description1: `The Zonda S uses a modified version of the V12 engine used in the C12 enlarged to 7.0 L (427 cu in). Tuned by Mercedes-AMG, the engine has a power output of 550 PS (405 kW; 542 hp) and is mated to a newly developed 6-speed manual transmission in order to handle the high power output produced by the engine.`,
        description2: `The Zonda S uses a modified version of the V12 engine used in the C12 enlarged to 7.0 L (427 cu in). Tuned by Mercedes-AMG, the engine has a power output of 550 PS (405 kW; 542 hp) and is mated to a newly developed 6-speed manual transmission in order to handle the high power output produced by the engine.`,
        images: 'Zonda S.jpg'
    },
    {
        name: 'Pagani Zonda Roadster',
        color: 'Grey',
        category: 'sport_cars',
        subCategory: 'Pagani',
        licensePlate: 'XXXX-YYY',
        vanSize: 2,
        driverLicense: 'B',
        description1: `Pagani presented the Zonda Roadster, an open top version of the Zonda S 7.3. Carrying the same components as the coupé, Pagani promised no loss of performance, a claim supported by the minimal weight gain of 30 kg (66 lb). A total of 40 roadsters were produced.`,
        description2: `Pagani presented the Zonda Roadster, an open top version of the Zonda S 7.3. Carrying the same components as the coupé, Pagani promised no loss of performance, a claim supported by the minimal weight gain of 30 kg (66 lb). A total of 40 roadsters were produced.`,
        images: 'Pagani Zonda Roadster.jpg'
    },
];

export default vehicles